// Generated by CoffeeScript 2.4.1
(function () {
  var prepend;

  prepend = (id, content) => {
    return document.getElementById(id).innerHTML = content;
  };

  prepend('nav-top', '<nav class="level navbar"> <div class="level-item has-text-centered"> <div> <p class="heading left-space">Welcome to</p> <p id="main-title" class="left-space">INSPIIIRED</p> </div> </div> </nav>');
  prepend('nav-footer', '<nav class="level"> <div class="level-item has-text-centered"> <nav class="breadcrumb"> <ul style="padding-top:2rem;"> <li class="is-active heading"><a href="https://github.com/Beyarz/inspiiired">Github</a></li> <li class="heading"><a href="https://github.com/Beyarz/inspiiired">Beyarz</a"></li> </ul> </nav> </div> </nav>');
}).call(this);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNpZ25hdHVyZS5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLENBQUEsWUFBQTtBQUFBLE1BQUEsT0FBQTs7QUFBQSxFQUFBLE9BQUEsR0FBVSxDQUFBLEVBQUEsRUFBQSxPQUFBLEtBQUE7V0FDUixRQUFRLENBQVIsY0FBQSxDQUFBLEVBQUEsRUFBQSxTQUFBLEdBQXdDLE87QUFEaEMsR0FBVjs7QUFHQSxFQUFBLE9BQUEsQ0FBQSxTQUFBLEVBQUEsb01BQUEsQ0FBQTtBQVdBLEVBQUEsT0FBQSxDQUFBLFlBQUEsRUFBQSxvVUFBQSxDQUFBO0NBZEEsRSxJQUFBLEMsSUFBQSIsInNvdXJjZXNDb250ZW50IjpbInByZXBlbmQgPSAoaWQsIGNvbnRlbnQpID0+XG4gIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKGlkKS5pbm5lckhUTUwgPSBjb250ZW50XG5cbnByZXBlbmQoJ25hdi10b3AnLCAnXG48bmF2IGNsYXNzPVwibGV2ZWwgbmF2YmFyXCI+XG4gIDxkaXYgY2xhc3M9XCJsZXZlbC1pdGVtIGhhcy10ZXh0LWNlbnRlcmVkXCI+XG4gICAgPGRpdj5cbiAgICA8cCBjbGFzcz1cImhlYWRpbmcgbGVmdC1zcGFjZVwiPldlbGNvbWUgdG88L3A+XG4gICAgPHAgaWQ9XCJtYWluLXRpdGxlXCIgY2xhc3M9XCJsZWZ0LXNwYWNlXCI+SU5TUElJSVJFRDwvcD5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L25hdj5cbicpXG5cbnByZXBlbmQoJ25hdi1mb290ZXInLCAnXG4gIDxuYXYgY2xhc3M9XCJsZXZlbFwiPlxuICAgIDxkaXYgY2xhc3M9XCJsZXZlbC1pdGVtIGhhcy10ZXh0LWNlbnRlcmVkXCI+XG4gICAgICA8bmF2IGNsYXNzPVwiYnJlYWRjcnVtYlwiPlxuICAgICAgICA8dWwgc3R5bGU9XCJwYWRkaW5nLXRvcDoycmVtO1wiPlxuICAgICAgICAgIDxsaSBjbGFzcz1cImlzLWFjdGl2ZSBoZWFkaW5nXCI+PGEgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9CZXlhcnovaW5zcGlpaXJlZFwiPkdpdGh1YjwvYT48L2xpPlxuICAgICAgICAgIDxsaSBjbGFzcz1cImhlYWRpbmdcIj48YSBocmVmPVwiaHR0cHM6Ly9naXRodWIuY29tL0JleWFyei9pbnNwaWlpcmVkXCI+QmV5YXJ6PC9hXCI+PC9saT5cbiAgICAgICAgPC91bD5cbiAgICAgIDwvbmF2PlxuICAgIDwvZGl2PlxuICA8L25hdj5cbicpXG4iXSwic291cmNlUm9vdCI6IiJ9
//# sourceURL=signature.coffee
